// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Close': string;
  'Controlled': string;
  'Controller': string;
  'FullTable': string;
  'Header': string;
  'Headers': string;
  'Level1': string;
  'Level2': string;
  'Level3': string;
  'Open': string;
  'SoloInfo': string;
  'TestBlock': string;
  'soloRom': string;
}
export const cssExports: CssExports;
export default cssExports;
